#include "redgrammm.h"
#include <stdbool.h>
#include <stdio.h>
#include <string.h>
#include <ctype.h>

bool is_expect(char *chaine);
bool is_from();
bool is_GMT(char *chaine);
bool is_http_date(char *chaine);
bool is_day_name(char *chaine);
bool is_day_name(char *chaine);
bool is_delay_seconds(char *chaine);
bool is_location(char *chaine);
bool is_max_forwards(char *chaine);
bool is_referer(char *chaine);
bool is_retry_after(char *chaine);
bool is_server();
bool is_charset(char *chaine);
bool is_product_version(char *chaine);
bool is_content_coding(char *chaine);
bool is_subtype(char *chaine);
bool is_type(char *chaine);
bool is_codings(char *chaine);
bool is_date2(char *chaine);
bool is_date1(char *chaine);
bool is_day(char *chaine);
bool is_hour(char *chaine);
bool is_minute(char *chaine);
bool is_second(char *chaine);
bool is_year(char *chaine);
bool is_month(char *chaine);
bool is_obs_date(char *chaine);
bool is_etag(char *chaine);
bool is_last_modified(char *chaine);
bool is_accept_ranges(char *chaine);
bool is_if_range(char *chaine);
bool is_range(char *chaine);
bool is_range_unit(char *chaine);
bool is_bytes_unit(char *chaine);
bool is_complete_length(char *chaine);
bool is_first_byte_pos(char *chaine);
bool is_last_byte_pos(char *chaine);
bool is_suffix_length(char *chaine);
bool is_suffix_byte_range_spec(char *chaine);
bool is_other_range_unit(char *chaine);
bool is_other_range_resp(char *chaine);
bool is_other_range_set(char *chaine);
bool is_other_content_range(char *chaine);
bool is_other_range_specifier(char *chaine);
bool is_weak(char *chaine);
bool is_user_agent(char *chaine);
bool is_vary(char *chaine);
bool is_accept_ext(char *chaine);
bool is_accept_params(char *chaine);
bool is_asctime_date(char *chaine);
bool is_date3(char *chaine);
bool is_media_range(char *chaine);
bool is_parameter(char *chaine);
bool is_product(char *chaine);
bool is_qvalue(char *chaine);
bool is_rfc850_date(char *chaine);
bool is_time_of_day(char *chaine);
bool is_weight(char *chaine);
bool is_if_match(char *chaine);
bool is_if_modified_since(char *chaine);
bool is_if_none_match(char *chaine);
bool is_unmodified_since(char *chaine);
bool is_entity_tag(char *chaine);
bool is_acceptable_ranges(char *chaine);
bool is_byte_content_range(char *chaine);
bool is_byte_range(char *chaine);
bool is_byte_range_resp(char *chaine);
bool is_byte_range_set(char *chaine);
bool is_byte_range_spec(char *chaine);
bool is_byte_range_specifier(char *chaine);